### ISSUE TITLE
主动发送客服消息

### ISSUE THREAD

**Issue by gavingy33** [yydzxz/ByteDance#5]
您好，这个接口是否可以添加上
消息推送客服
https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/component/message-push-customer-service/

**Comment by yydzxz** [comment]
我尽快吧

**Comment by gavingy33** [comment]
https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/server/ecpay/introduction
好像担保支付这块功能也是缺少的
